/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as BecomeACaptainRouteImport } from './routes/become-a-captain'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicFishxWebhookRouteImport } from './routes/api/public/fishx-webhook'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeACaptainRoute = BecomeACaptainRouteImport.update({
  id: '/become-a-captain',
  path: '/become-a-captain',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicFishxWebhookRoute = ApiPublicFishxWebhookRouteImport.update({
  id: '/api/public/fishx-webhook',
  path: '/api/public/fishx-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-captain': typeof BecomeACaptainRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/trust': typeof TrustRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/b/$slug': typeof BSlugRoute
  '/api/public/fishx-webhook': typeof ApiPublicFishxWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-a-captain': typeof BecomeACaptainRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/trust': typeof TrustRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/b/$slug': typeof BSlugRoute
  '/api/public/fishx-webhook': typeof ApiPublicFishxWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-a-captain': typeof BecomeACaptainRoute
  '/discover': typeof DiscoverRoute
  '/how-it-works': typeof HowItWorksRoute
  '/trust': typeof TrustRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/b/$slug': typeof BSlugRoute
  '/api/public/fishx-webhook': typeof ApiPublicFishxWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-a-captain'
    | '/discover'
    | '/how-it-works'
    | '/trust'
    | '/dashboard'
    | '/onboarding'
    | '/b/$slug'
    | '/api/public/fishx-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-a-captain'
    | '/discover'
    | '/how-it-works'
    | '/trust'
    | '/dashboard'
    | '/onboarding'
    | '/b/$slug'
    | '/api/public/fishx-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/become-a-captain'
    | '/discover'
    | '/how-it-works'
    | '/trust'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/b/$slug'
    | '/api/public/fishx-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeACaptainRoute: typeof BecomeACaptainRoute
  DiscoverRoute: typeof DiscoverRoute
  HowItWorksRoute: typeof HowItWorksRoute
  TrustRoute: typeof TrustRoute
  BSlugRoute: typeof BSlugRoute
  ApiPublicFishxWebhookRoute: typeof ApiPublicFishxWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-captain': {
      id: '/become-a-captain'
      path: '/become-a-captain'
      fullPath: '/become-a-captain'
      preLoaderRoute: typeof BecomeACaptainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/fishx-webhook': {
      id: '/api/public/fishx-webhook'
      path: '/api/public/fishx-webhook'
      fullPath: '/api/public/fishx-webhook'
      preLoaderRoute: typeof ApiPublicFishxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeACaptainRoute: BecomeACaptainRoute,
  DiscoverRoute: DiscoverRoute,
  HowItWorksRoute: HowItWorksRoute,
  TrustRoute: TrustRoute,
  BSlugRoute: BSlugRoute,
  ApiPublicFishxWebhookRoute: ApiPublicFishxWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
