// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zibmbgvhretnuvgiytmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppYm1iZ3ZocmV0bnV2Z2l5dG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4MzQxMTcsImV4cCI6MjA5ODQxMDExN30.9ddsugSrpePiTJKKCoN2VPhGj7BvPXq6Ylfceajq5jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});